### ISSUE TITLE
Not getting any output from howdoi

### ISSUE THREAD

**Issue by masonc15** [san-kumar/howdoi#2]
Hello,

I just installed howdoi and when I just type `howdoi`,  I get the usage guide but after I type the example howdoi about extracting a tar file, I do not get any output back.  Any help would be appreciated.  Thanks!

**Comment by san-kumar** [comment]
That's strange. I've added a debug mode to it. Can you please try `howdoi -d shutdown` and paste the entire content here.

**Comment by masonc15** [comment]
The output is too long to post as a comment here.  Let me know if you view the output at this [Pastebin](https://pastebin.com/0zBGvPJ7).  Thanks!

**Comment by san-kumar** [comment]
Hi, you can fix the errors by following the steps here:

https://stackoverflow.com/questions/14395239/class-domdocument-not-found

Please open another ticket if this doesn't work. thanks.

**Comment by masonc15** [comment]
Hello,

Thanks for the response.  For reference, the following command fixed the issue for me:
`apt-get install php-xml`

Thanks!
