### ISSUE TITLE
PHP Fatal error:  Can't use function return value in write context in /root/bin/howdoi on line 19

### ISSUE THREAD

**Issue by justsheep** [san-kumar/howdoi#3]
`mkdir -p ~/bin && wget https://raw.githubusercontent.com/san-kumar/howdoi/master/howdoi -O ~/bin/howdoi && chmod +x ~/bin/howdoi`
it's ok.
`sudo ln -s ~/bin/howdoi /usr/local/bin/howdoi`
it's ok.
`howdoi check my linux version`
`PHP Fatal error:  Can't use function return value in write context in /root/bin/howdoi on line 19`
how can I solve this problem?

**Comment by san-kumar** [comment]
this looks like a problem with your php setup.

1. Can you tell me which PHP version you are using? 
2. Can you upgrade to PHP 7+ and try with that?

**Comment by justsheep** [comment]
> this looks like a problem with your php setup.
> 
> 1. Can you tell me which PHP version you are using?
> 2. Can you upgrade to PHP 7+ and try with that?

oh, yum install php is php5
now, I compiled php7
