### ISSUE TITLE
howdoi no response in wsl ubuntu 20.04?

### ISSUE THREAD

**Issue by mkitby** [san-kumar/howdoi#4]
Hi,

PHP 7.4 is installed, and installed the howdoi as README.md. but howdoi  has nothing output.

➜  ~ howdoi extract a bz2 file
➜  ~

**Comment by san-kumar** [comment]
Can you post the output of 

`howdoi -d extract a bz2 file`

**Comment by san-kumar** [comment]
Closing for now because no follow up response.
